version: '3.4'

services:
  e-journal.server:
    image: ${DOCKER_REGISTRY-}ejournalserver
    build:
      context: .
      dockerfile: E-Journal.Server/Dockerfile
    expose:
      - 443
      - 80
    depends_on:
      - e-journal.mysql

  e-journal.mysql:
    image: mysql
    command: --innodb_use_native_aio=0
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
    hostname: mysql
    container_name: e-journal.mysql


