version: '3.4'

name: 'e_journal'

services:
  e-journal.schedulesapi:
    image: ${DOCKER_REGISTRY-}ejournalschedulesapi
    container_name: schedulesapi
    build:
      context: .
      dockerfile: E-Journal.SchedulesApi/Dockerfile
    restart: always
    depends_on:
      - e-journal.sqldb

  e-journal.journalapi:
    image: ${DOCKER_REGISTRY-}ejournaljournalapi
    container_name: journalapi
    build:
      context: .
      dockerfile: E-Journal.JournalApi/Dockerfile
    restart: always
    depends_on:
      - e-journal.sqldb

  e-journal.sqldb:
    image: mariadb
    container_name: sqldb
    command: --innodb_use_native_aio=0
    volumes:
      - sql_data:/var/lib/mysql

volumes:
  sql_data: 