version: '3.4'

services:
  e-journal.schedulesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
      - SCHEDULES_DB_CONNECTION_STRING=Server=schedulesdb;Port=5432;Database=schedules;User Id=postgres;Password=postgres;
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  e-journal.schedulesdb:
    expose:
      - 5432
    environment:
      - POSTGRES_DB=schedules
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    