version: '3.4'

name: 'e_journal'

services:
  e-journal.schedulesapi:
    image: ${DOCKER_REGISTRY-}ejournalschedulesapi
    container_name: schedulesapi
    build:
      context: .
      dockerfile: E-Journal.SchedulesApi/Dockerfile
    restart: always
    