version: '3.4'

services:
  e-journal.schedulesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
      - SCHEDULES_DB_CONNECTION_STRING=Server=schedulesdb;Port=3306;Database=schedules;User=root;Password=12345;
      - UPDATE_CHECK_FREQUENCY_MINUTES=30
      - BUILDING_1_GROUP_DAYLY_SCHEDULE_URL=http://mgke.minsk.edu.by/ru/main.aspx?guid=3831
      - BUILDING_2_GROUP_DAYLY_SCHEDULE_URL=http://mgke.minsk.edu.by/ru/main.aspx?guid=3841
      - BUILDING_1_GROUP_WEEKLY_SCHEDULE_URL=http://mgke.minsk.edu.by/ru/main.aspx?guid=3781
      - BUILDING_2_GROUP_WEEKLY_SCHEDULE_URL=http://mgke.minsk.edu.by/ru/main.aspx?guid=3791
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  e-journal.schedulesdb:
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=schedules
      