version: '3.4'

services:
  e-journal.schedulesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5011;http://+:5010
      - ASPNETCORE_HTTPS_PORT=5011
      - SCHEDULES_DB_CONNECTION_STRING=Server=sqldb;Port=3306;Database=SchedulesDB;User=root;Password=12345;
      - UPDATE_CHECK_FREQUENCY_MINUTES=30
      - BUILDING_1_GROUP_DAYLY_SCHEDULE_URL=http://mgke.minsk.edu.by/ru/main.aspx?guid=3831
      - BUILDING_2_GROUP_DAYLY_SCHEDULE_URL=http://mgke.minsk.edu.by/ru/main.aspx?guid=3841
      - BUILDING_1_GROUP_WEEKLY_SCHEDULE_URL=http://mgke.minsk.edu.by/ru/main.aspx?guid=3781
      - BUILDING_2_GROUP_WEEKLY_SCHEDULE_URL=http://mgke.minsk.edu.by/ru/main.aspx?guid=3791
    expose:
      - "5010"
      - "5011"
    ports:
      - "5010:5010"
      - "5011:5011"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  e-journal.journalapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5021;http://+:5020
      - ASPNETCORE_HTTPS_PORT=5021
      - JOURNAL_DB_CONNECTION_STRING=Server=sqldb;Port=3306;Database=JournalDB;User=root;Password=12345;
    expose:
      - "5020"
      - "5021"
    ports:
      - "5020:5020"
      - "5021:5021"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  e-journal.sqldb:
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      